#!/usr/bin/env bash
##################################################################
##
##  Add script description here
##
##
##  Author: Chaobin Wu
##  Email : chaobinwu89@gmail.com
##
#################################################################
arg="arg"
if [ $# == 0 ]; then
  script="${0##*/}"
	echo "Usage: $script $arg"
	exit 1
fi
die() {
  echo "$*"
  exit 1
}
name="$1"
file="leetcode/$name.md"
touch $file
echo "# $name" >> $file
echo "## 题目" >>$file
echo "" >>$file
echo "## 思路&题解" >>$file
echo "" >>$file
echo "## 知识点分析" >>$file
