title: Hacktons # your site title
author: 小文字
email: me@hacktons.cn # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  hacktons主要用于汇总笔者的个人开发项目，包括翻译的教程，编写的主题专栏等。
  范围涉及软件开发各领域技术栈，如Android, React, Nodejs，Golang，Shell
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://hacktons.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  hacktons # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer
#social:
#  name: Your Name
#  links:
#    - https://twitter.com/BenBalter
#    - https://www.facebook.com/ben.balter
#    - https://www.linkedin.com/in/BenBalter
#    - https://plus.google.com/+BenBalter
#    - https://github.com/benbalter
#    - https://keybase.io/benbalter

#disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
